# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml333

trigger: none    # Disable CI trigger (on push)

pr:
  branches:
    include:
      - main      # Trigger only when PR targets 'main' branch

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Adding a PowerShell script with timeout
- powershell: |
    Write-Host "This is a PowerShell script with a timeout."
    Start-Sleep -Seconds 120  # Simulate a longer-running task
  displayName: 'Run PowerShell script with 1-minute timeout'
  timeoutInMinutes: 1  # Timeout set to 1 minute
